barber/appointment/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.queue,name='queue')
    
]

app_name='appointment'

barber/barber_pj/urls.py
from django.contrib import admin
from django.urls import path,include







urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
    path('login/',include("login.urls")),
    path('gallery/',include("gallery.urls")),
    path('queue/',include('appointment.urls')),
    path('contact/',include('contact.urls'))
]

barber/contact/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.contact,name='contact')
    
]

app_name='contact'

barber/gallery/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.gallery,name='gallery')
    
]

app_name='gallery'

barber/homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.start,name='home')
    
]

app_name='homepage'

barber/login/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.login,name='login'),
    path('register/',views.register,name='register')
    
]

app_name='login'

barber/appointment/models.py
from django.db import models
import datetime
import calendar

# Create your models here.


class Date(models.Model):
    year=models.IntegerField()
    month=models.IntegerField()
    day=models.IntegerField()
    date=models.DateField()

barber/contact/models.py
from django.db import models

# Create your models here.

barber/gallery/models.py
from django.db import models

# Create your models here.

barber/homepage/models.py
from django.db import models

# Create your models here.

barber/login/models.py
from django.db import models


# Create your models here.

barber/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ( "email","first name","last name", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

barber/appointment/views.py
from django.shortcuts import render


# Create your views here.


def queue(request):
    return render(request,'appointment/queue.html')

barber/contact/views.py
from ast import Return
import re
from django.shortcuts import render

# Create your views here.


def contact(request):
    return render(request,'contact/contact.html')

barber/gallery/views.py
from django.shortcuts import render

# Create your views here.

def gallery(request):
    return render(request,'gallery/gallery.html')

barber/homepage/views.py
from django.shortcuts import render


# Create your views here.

def start(request):
    return render(request,'homepage/home_page.html')

barber/login/views.py
from django.shortcuts import render

# Create your views here.


def login(request):
    return render(request,'login/login.html')


def register(request):
    return render (request,'login/register.html')



        
        
            
            

barber/appointment/templates/appointment/queue.html
{% extends 'homepage/home_page.html' %}

{% block 'home' %}
{% load static %}


{% endblock 'home' %}

barber/contact/templates/contact/contact.html
{% extends 'homepage/home_page.html' %}

{% block 'home' %}
{% load static %}


{% endblock 'home' %}

barber/gallery/templates/gallery/gallery.html
{% extends 'homepage/home_page.html' %}

{% block 'home' %}
{% load static %}


{% endblock 'home' %}

barber/login/templates/login/login.html
{% extends 'homepage/home_page.html' %}

{% block 'home' %}
{% load static %}
<link rel="stylesheet" href="{% static 'login/css/queue.css' %}">
<form   method="POST">
    <div class="container">
      <h1>Log in</h1>
      <h3>Please fill in this form to connect</h3>
      <hr>
      {% csrf_token %}

  
      <label ><b>Email</b></label>
      <input type="text" placeholder="Enter Email"  required>

  
      <label ><b>Password</b></label>
      <input type="password" placeholder="Enter Password"  required>
  
      <button type="submit" class="registerbtn">Log in</button>
    </div>
  
    <div class="container signin">
      <p>You do not have an account yet? <a href="{% url 'login:register' %}">Register</a>.</p>
    </div>
  </form>

{% endblock 'home' %}

barber/login/templates/login/register.html
{% extends 'homepage/home_page.html'%}

{% block 'home' %}
{% load static %}
  <link rel="stylesheet" href="{% static 'login/css/queue.css' %}">
  <form   method="POST">
    <div class="container">
      <h1>Register</h1>
      <h3>Please fill in this form to create an account.</h3>
      <hr>
      {% csrf_token %}

      <label><b>Email</b></label>
      <input type="text" placeholder="Enter Email"  required>

      <label >First name:</label>
      <input type="text" placeholder="Enter first name"   required>

      <label >Last name:</label>
      <input type="text" placeholder="Enter last name" required>
  
      <label ><b>Password</b></label>
      <input type="password" placeholder="Enter Password"  required>
  
      <label ><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password"  required>
      <hr>
  
      <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
      <button  type="submit" class="registerbtn">Register</button>
    </div>
  
    <div class="container signin">
      <p>Already have an account? <a href="{% url 'login:login' %}">Sign in</a>.</p>
    </div>
  </form>

{% endblock  %}

barber/templates/homepage/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'homepage/css/design.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,1000&display=swap" rel="stylesheet">
    <script src="{% static 'homepage/js/home.js' %}"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barbershop- Ran hasin מספרת גברים - מספרה בחדרה</title>
</head>
<body class="backg">

    <div class="topnav">

        <a class="active" href="{% url 'homepage:home' %}" ><i class="bi bi-house-fill"></i></a>

        <a href="{% url 'login:register' %}">התחבר/הירשם</a>
    
        <div class="topnav-right">

            <button class="openbtn" onclick="openNav()">☰</button> 
            
            <a href=""><i class="bi bi-facebook"></i></a>
            
            <a href="https://www.instagram.com/ranhasin/"><i class="bi bi-instagram"></i></a>
           
            <a href="https://wa.me/972548352202"><i class="bi bi-whatsapp"></i></a>
            
            <div id="panel" class="sidepanel">
                
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">x</a>
                
                <a href="{% url 'appointment:queue' %}">קבע תור עכשיו</a>
                
                <a href="{% url 'contact:contact' %}">צור קשר</a>
                
                <a href="{% url 'gallery:gallery' %}">גלריה</a></div>
                
            </div>

        </div> 

      
        {% block 'home' %}
        
        <div>
            <br>
            <br>
            <br>
            
            <div class="info">
            
                <h1 style="margin-bottom: 12.0pt; text-align: center;"><span ><strong><span style="color: rgb(255, 255, 255);">  Ran Hasin - Barbershop </span></strong></span></h1>
            
                <p style="margin-bottom: 12.0pt; text-align: center;"><span style="font-size: 18pt;"><strong><span style="color: rgb(255, 255, 255);">שעות פעילות המספרה  </span></strong></span></p>
            
                <p style="text-align: center;"><span style="font-size: 18pt; color: rgb(255, 255, 255);">&nbsp;א'-ה': 20:00-9:00  </span></p>
            
                <p style="text-align: center;"><span style="font-size: 18pt; color: rgb(255, 255, 255);">יום ו': 14:00-8:00  </span></p></div>
            
                <p style="text-align: center;"><span style="font-size: 18pt; color: rgb(255, 255, 255);"></span></p>
            
                <p style="text-align: center;"></p>
        
    </div>

      {% endblock 'home' %}

</body>
</html>